spring:
  application:
    name: oms

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        enhancer:
          enableAssociationManagement: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cloud:
    function:
      definition: none

  datasource:
    url: jdbc:postgresql://localhost:5432/oms
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: secret


  sql:
    init:
      mode: never

  devtools:
    add-properties: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: oms
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.p2p.oms: INFO
    root: INFO
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: INFO
    org.springframework.boot: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.springframework.integration: WARN
    org.hibernate.orm.tooling.maven: ERROR
    org.hibernate.bytecode.enhance: ERROR
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"